swagger: '2.0'
info:
  title: dobby
  description: "Dobby (DB) Services for Doc AI Demo"
  version: 1.0.0
schemes:
- https
produces:
- application/json
x-google-backend:
  address: https://dobby-6l773bwsva-uw.a.run.app
security:
 - api_key: []
paths:
  /file_data:
    get:
      summary: "Get data about the file from bigquery"
      operationId: fileData
      parameters:
        - in: query
          name: fileId
          type: string
          description: "The UUID of the file"
          required: true
      responses:
        200:
          description: "The entities object of file"
          schema:
            type: object
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"