steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  args:
  - build
  - -t
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_NAME/file-processor
  - --build-arg
  - dataset=${_DATASET}
  - --build-arg
  - processorId=${_PROCESSOR_ID}
  - --build-arg
  - projectId=$PROJECT_ID
  - src/fileprocessorservice
- name: 'gcr.io/cloud-builders/docker'
  id: push
  args:
  - push
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_NAME}/file-processor
  waitFor:
    - build
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - document-processor
  - --image
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_NAME}/file-processor
  - --region
  - ${_REGION}
  waitFor:
    - push